### ISSUE TITLE
character animation

### ISSUE THREAD

**Issue by yiruniu** [yiruniu/shadowpuppet#1]
hi, I got problem for my character moving. I want to when I hover on my character arm the start to  move right to left. 
but wen I write css

.sp-lefcharacter-leftarm:hover{
  width: 60%;
  position: absolute;
  left: 5%;
  top: 38%;
  transform: rotateY(45deg);
   transition-origin:top left;
   transform 1s;
  }

the character become:
<img width="679" alt="Screen Shot 2021-10-05 at 12 58 41 PM" src="https://user-images.githubusercontent.com/91919877/135940448-5affe681-c33d-4b78-9318-4a42017d19df.png">

<img width="769" alt="Screen Shot 2021-10-05 at 1 04 50 PM" src="https://user-images.githubusercontent.com/91919877/135940577-c028c9ce-b1dd-4f51-b414-0d735a535e54.png">

how can I change that

**Comment by ellysmlly** [comment]
Ok awesome! This is a great start and your character is looking really good 

I've found the issue and described below:

The code snippet you have is only applying styles when you are **hovering** on the left arm. This means that when you are **not hovering** on the left arm there is no CSS being applied to your image and your character is broken

> .sp-lefcharacter-leftarm:hover{
>     width: 60%;
>     position: absolute;
>     left: 5%;
>     top: 38%;
>     transform: rotateY(45deg);
>     transition-origin:top left;
>     transform 1s;
>  }

To fix this you need to have styles that are always applied even when hovering or not. I have also added a few notes to your css rules where there were errors

Answer:

These styles will always be applied to your left arm

> .sp-lefcharacter-leftarm {
>     width: 60%;
>     position: absolute;
>     left: 4%;
>     top: 44%;
>     transform: rotate(15deg);
>     /* this needed to change to right not left */
>     /* and this style property is transform-origin not transition-origin */
>     transform-origin: top right;
>      /* this style property is transition not transform */
>     transition: all 1s;
>  }

These styles will be applied only when hovering on the left arm

> .sp-lefcharacter-leftarm:hover {
>      /* you can update this rotation amount  */
>     transform: rotate(-15deg);
>     transition: all 1s;
>  }

@yiruniu let me know if you have more questions, I would spend a little bit of time reviewing your code with the right tabbing too
@sehsarah do you want to add anything?

**Comment by sehsarah** [comment]
sounds good to me! give that a go @yiruniu and let us know how u go

**Comment by yiruniu** [comment]
thank you to reply me , it  help me a lot.

**Comment by ellysmlly** [comment]
No worries Yiru - if you want to make those updates and then tag me again here when you re-upload the files to github. I can review and double check its working correctly
