### ISSUE TITLE
character animation and background element moving

### ISSUE THREAD

**Issue by yiruniu** [yiruniu/shadowpuppet#2]
2 questions:

1. I rewrite my css and html, but when the character arm moving ,it is quick weird

<img width="653" alt="Screen Shot 2021-10-11 at 3 20 08 PM" src="https://user-images.githubusercontent.com/91919877/136724459-bb55df4c-81c4-4b6f-8132-0c14731095c1.png">

css
```
.sp-character-rightarm{
     width: 105%;
     position: absolute;
     left: 45%;
     top: 40%;
     transform:rotate(2deg);
     transform-origin:top right;
    }
    .sp-character-rightarm:hover {
    transform:rotate(0deg);
    transition: all 1s;
    }
   ```
   
I want the character's arm left to right moving , not  going down.

The second thing is that
The background image .  

<img width="858" alt="Screen Shot 2021-10-11 at 3 25 56 PM" src="https://user-images.githubusercontent.com/91919877/136725148-e4df8c09-4dcd-477c-9209-d27d0bbd58e0.png">

css:
```
.sp-background-topright{
position: absolute;
float:left;
top:0%;
left:0%;
width:100%;
}
.sp-background-bottomleft{
position: absolute;
bottom:0%;
left:0%;
width:80%;
}
```
```
.sp-background-bottomright{
position: absolute;
float: left;
width: 120%;
bottom:0%;
right:0%;
  }
  ```
  
I want my top-right image close to the web edge and bottom two image showing  . 

@sehsarah @ellysmlly

**Comment by yiruniu** [comment]
Hello Sarah and Elly:
I know why the two image didn't showing , but I still don't know how to fix the right arm and right side image.
now I had new problem .
I'm writing  lion dance web, I  want the lion lower body shake. 
 

<img width="960" alt="Screen Shot 2021-10-15 at 3 52 04 PM" src="https://user-images.githubusercontent.com/91919877/137425161-a09948c3-1bc5-4411-8028-85593bbe1041.png">

css:
....
.ld-character-yellowcolor-container{
  position:relative;
  width:50%;
  left:40%;

}
.ld-character-yellowcolor-head{
  position:absolute;
  top:70%;
  left:10%;
  width:50%;

}
.ld-character-yellowcolor-lowerbody{
  position:absolute;
  top:55%;
  bottom:30%;
  left:50%;
  width:20%;
  animation:shake .8s ease-in;
}
@keyframes shake{
  0%{transform:translate(0);
  }
  20%,
  40%,
  60%,
  80%{
    transform: translate(.8em);
  }
  10%,
  30%,
  50%{
    transform:translate(-,2em);
    }
    70%,
    100%{
      transform:translate(0);
    }
}

 
it doesn't moving, could help me to check . thanks 
@sehsarah@ellysmlly

**Comment by ellysmlly** [comment]
Hey @yiruniu I think all of these were answered on our 1:1 

You can close this issue if they are all answered
